18BCE084

Kaushal Jani

Prac6

In [53]:
import sklearn
from sklearn import metrics,datasets
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn import model_selection

In [54]:
# spliting data
X,Y=datasets.load_iris(return_X_y=True)

xtrain=X[range(0,150,2),:]
ytrain=Y[range(0,150,2)]
xtest=X[range(1,150,2),:]
ytest=Y[range(1,150,2)]

# making instance of id3 classifier
print("Classification Using ID3 ")
clf=DecisionTreeClassifier(criterion='entropy')
#learning the classifier
clf.fit(xtrain,ytrain)
#predicting the class
ypred=clf.predict(xtest)

print("accuracy ",metrics.accuracy_score(ytest,ypred))
print("confussion metrics ",metrics.confusion_matrix(ytest,ypred))
print()
print(metrics.classification_report(ytest, ypred))
print()

# CART 

print("classification using CART ")
# making instance of cart classifier
model = DecisionTreeClassifier(criterion='gini')
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
print("accuracy ",metrics.accuracy_score(ytest,ypred))
print("confussion metrics ",metrics.confusion_matrix(ytest,ypred))
print()
print(metrics.classification_report(ytest, ypred))
print()

Classification Using ID3 
accuracy  0.96
confussion metrics  [[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75


classification using CART 
accuracy  0.96
confussion metrics  [[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75




Decision Tree in ***CATEGORICAL*** Data

In [55]:
import pandas as pd
import csv
import random 
from sklearn import preprocessing
from sklearn.metrics import classification_report 

In [56]:
trend = 'up,down,down,down,up,up,down,up,up,up,down,down,down,up,down,up,down,up,up,down'.split(',')
variance = 'low,high,low,normal,high,low,normal,high,normal,low,normal,normal,high,high,low,high,high,normal,normal,low'.split(',')
buys = 'yes,no,no,no,yes,yes,yes,no,yes,yes,no,yes,no,yes,yes,no,no,yes,yes,no'.split(',')
table={'trend':trend,'variance':variance,'Purchase':buys}
df = pd.DataFrame(table)
df




trend variance Purchase
0     up      low      yes
1   down     high       no
2   down      low       no
3   down   normal       no
4     up     high      yes
5     up      low      yes
6   down   normal      yes
7     up     high       no
8     up   normal      yes
9     up      low      yes
10  down   normal       no
11  down   normal      yes
12  down     high       no
13    up     high      yes
14  down      low      yes
15    up     high       no
16  down     high       no
17    up   normal      yes
18    up   normal      yes
19  down      low       no

In [57]:
label_encoder = preprocessing.LabelEncoder()

for i in df:
  df[i] = label_encoder.fit_transform(df[i])
print("After preprocessing ")
df

After preprocessing 


trend  variance  Purchase
0       1         1         1
1       0         0         0
2       0         1         0
3       0         2         0
4       1         0         1
5       1         1         1
6       0         2         1
7       1         0         0
8       1         2         1
9       1         1         1
10      0         2         0
11      0         2         1
12      0         0         0
13      1         0         1
14      0         1         1
15      1         0         0
16      0         0         0
17      1         2         1
18      1         2         1
19      0         1         0

In [58]:
data = df[['trend','variance']]
out = df['Purchase']
x_train, x_test, y_train, y_test = model_selection.train_test_split(data, out, test_size = 0.30)
print(x_train)


    trend  variance
5       1         1
0       1         1
17      1         2
7       1         0
4       1         0
12      0         0
2       0         1
18      1         2
16      0         0
11      0         2
14      0         1
3       0         2
8       1         2
6       0         2


In [59]:
print("For ID3\n")
clf = DecisionTreeClassifier(criterion = 'entropy')

clf.fit(x_train, y_train)
ypred = clf.predict(x_test)
print(ypred)
print('Accuracy', metrics.accuracy_score(y_test, ypred, normalize = True))

print("For CART\n")
clf = DecisionTreeClassifier(criterion = 'gini')
clf.fit(x_train, y_train)
ypred = clf.predict(x_test)

print(ypred)
print('Accuracy', metrics.accuracy_score(y_test, ypred, normalize = True))


For ID3

[1 0 1 0 0 0]
Accuracy 0.6666666666666666
For CART

[1 0 1 0 0 0]
Accuracy 0.6666666666666666
