Kaushal Jani

**Practical 8** 

**Liner SVM**

In [1]:
import sklearn
from sklearn import svm,datasets,metrics

In [2]:
X,Y = datasets.load_iris(return_X_y=True)
xtrain  = X[range(0,150,2),:]
ytrain  = Y[range(0,150,2)]
xtest   = X[range(1,150,2),:]
ytest  = Y[range(1,150,2)]


# linear svm

clf = svm.LinearSVC()
clf.fit(xtrain,ytrain)
ypred=clf.predict(xtest)
print("ACCURACY ",metrics.accuracy_score(ytest,ypred))
print("REPORT ",metrics.classification_report(ytest,ypred))
print("Confusion Metrix ",metrics.confusion_matrix(ytest,ypred))


ACCURACY  0.96
REPORT                precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

Confusion Metrix  [[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


**Grid** **Search**

In [4]:
import numpy as np
import sklearn
from sklearn import datasets,metrics,neighbors
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Grid search for knn

In [6]:
X,Y =datasets.load_iris(return_X_y=True)
xtrain=X[range(0,150,2),:]
xtest=X[range(1,150,2),:]
ytrain=Y[range(0,150,2)]
ytest=Y[range(1,150,2)]

clf = neighbors.KNeighborsClassifier()
grid = {'n_neighbors':[1,5,7,11,17],'weights':['distance','uniform']}
gs = GridSearchCV(clf,param_grid=grid,cv=5)
clf=gs
clf.fit(xtrain,ytrain)
print("best params are\n"+str(clf.best_params_))
ypred=clf.predict(xtest)
print("Actual:",ytest)
print("Predicted:",ypred)
print(metrics.classification_report(ytest,ypred))
print(metrics.confusion_matrix(ytest,ypred))
print("\n accuracy",metrics.accuracy_score(ytest,ypred))

best params are
{'n_neighbors': 5, 'weights': 'distance'}
Actual: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]

 accuracy 0.9866666666666667


Grid search for multiple regression

In [7]:
X,Y=datasets.load_boston(return_X_y=True)
temp=np.ones(shape=(300,1))
xtrain=X[0:300,:]
xtrain=np.append(temp,xtrain,axis=1)
#print(xtrain[:10,:])
ytrain=Y[0:300]
ytrain=ytrain.astype('int')
xtest=np.append(np.ones(shape=(206,1)),X[300:,:],axis=1)
ytest=Y[300:]
ytest=ytest.astype('int')

model=StandardScaler()
model.fit(xtest)
xtest=model.transform(xtest)
model.fit(xtrain)
xtrain=model.transform(xtrain)

param_grid = {'alpha': [100, 1000, 10000], 'max_iter': [100,5000, 500]}
clf = SGDClassifier()
gs = GridSearchCV(clf, param_grid, cv=5)
clf=gs
clf.fit(xtrain, ytrain)
print(clf.best_params_)
ypred=clf.predict(xtest)
print(ypred)
print("MSE ",metrics.mean_squared_error(ytest,ypred));
print("MSA ",metrics.mean_absolute_error(ytest,ypred));


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


{'alpha': 10000, 'max_iter': 500}
[15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
MSE  70.16990291262135
MSA  6.004854368932039
